steps:
  - label: Select Configuration “:python:”    
    block: "Build"
    fields:
      - select: "Rom"
        key: "SCRIPTROM"
        hint: "What rom do you want compile? :codeclimate:"
        required: false
        default: "aicp"
        options:
          - label: "Aicp"
            value: "aicp"
          - label: "Aex"
            value: "aex"
          - label: "Altair"
            value: "altair"
          - label: "AOKP"
            value: "aokp"
          - label: "Aoscp"
            value: "aoscp"
          - label: "Aosip"
            value: "aosip"
          - label: "Arrow"
            value: "arrow"
          - label: "Bootleggers"
            value: "bootleggers"
          - label: "Candy"
            value: "candy"
          - label: "Carbon"
            value: "carbon"
          - label: "Citrus"
            value: "citrus"
          - label: "Colt"
            value: "colt"
          - label: "Corvus"
            value: "corvus"
          - label: "Cosmic"
            value: "cosmic"
          - label: "COSP"
            value: "cosp"
          - label: "CrDroid"
            value: "crdroid"
          - label: "Derpfest"
            value: "derpfest"
          - label: "Dot"
            value: "dot"
          - label: "Floko"
            value: "floko"
          - label: "Havoc"
            value: "havoc"
          - label: "Ion"
            value: "ion"
          - label: "Lineage"
            value: "lineage"
          - label: "Lotus"
            value: "lotus"
          - label: "Nitrogen"
            value: "nitrogen"
          - label: "Paranoid"
            value: "paranoid"
          - label: "Reloaded"
            value: "reloaded"
          - label: "RenouveauOS"
            value: "renouveaus"
          - label: "RevengeOS"
            value: "revenge"
          - label: "Resurrection Remix" 
            value: "resurrectionremix"
          - label: "Stag"
            value: "stag"
          - label: "StatiX"
            value: "statix"
          - label: "Superior"
            value: "superior"
          - label: "Viper"
            value: "viper"
          - label: "Xenon HD"
            value: "xenon"
          - label: "Xtended"
            value: "xtended"
      - select: "Sync"
        key: "SCRIPTSYNC"
        required: true
        default: "no"
        options:
          - label: "Yes"
            value: "yes"
          - label: "No"
            value: "no"
      - select: "Patch"
        key: "SCRIPTPATCH"
        required: true
        default: "no"
        options:
          - label: "Yes"
            value: "yes"
          - label: "Gapps"
            value: "gapps"
          - label: "No"
            value: "no"         
      - select: "Build"
        key: "BUILDROM"
        required: true
        default: "no"
        options:
          - label: "Yes"
            value: "yes"
          - label: "No"
            value: "no"
      - select: "Upload Rom"
        key: "UPLOADROM"
        required: true
        default: "no"
        options:
          - label: "Yes"
            value: "yes"
          - label: "No"
            value: "no"
      - select: "Clean dir"
        key: "ROMCLEAN"
        required: true
        default: "no"
        options:
          - label: "Make Clean"
            value: "make"
          - label: "Delete old Build"
            value: "zip"
          - label: "Delete all Folder"
            value: "delete"
          - label: "Delete all Folder except .repo"
            value: "reset"
          - label: "Nothing"
            value: "no"
 
  - label: Building “:github:”
    command: python3 /home/jimgsey/script/build.py $$(buildkite-agent meta-data get SCRIPTROM) $$(buildkite-agent meta-data get SCRIPTSYNC) $$(buildkite-agent meta-data get SCRIPTPATCH) $$(buildkite-agent meta-data get BUILDROM) $$(buildkite-agent meta-data get UPLOADROM) $$(buildkite-agent meta-data get ROMCLEAN)

    artifact_paths:
      - "/home/jimgsey/Android/Tools/Log/upload/build-*.log"  
    retry:
      manual: true
